- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/nvim-setup.yml

